In [ ]:
# Lesson from 1 pandas series and data frames
# https://meds-eds-220.github.io/MEDS-eds-220-course/book/chapters/lesson-2-series-dataframes.html

In [1]:
import pandas as pd
import numpy as np

In [2]:
# A numpy array
arr = np.random.randn(4) # random values from std normal distribution
print(type(arr))
print(arr, "\n")

# A pandas series made from the previous array
s = pd.Series(arr)
print(type(s))
print(s)

<class 'numpy.ndarray'>
[-0.03948165 -0.0555106   1.88711043 -0.06736913]

<class 'pandas.core.series.Series'>
0   -0.039482
1   -0.055511
2    1.887110
3   -0.067369
dtype: float64

In [4]:
# The basic method to create a pandas.Series is to call
# s = pd.Series(data, index=index)

In [5]:
# A series from a numpy array 
pd.Series(np.arange(3), index=[2023, 2024, 2025])

2023    0
2024    1
2025    2
dtype: int64

In [6]:
# A series from a list of strings with default index
pd.Series(['EDS 220', 'EDS 222', 'EDS 223', 'EDS 242'])

0    EDS 220
1    EDS 222
2    EDS 223
3    EDS 242
dtype: object

In [8]:
# Construct dictionary
d = {'key_0':2, 'key_1':'3', 'key_2':5}

# Initialize series using a dictionary
pd.Series(d)

key_0    2
key_1    3
key_2    5
dtype: object

In [9]:
pd.Series(3.0, index = ['A', 'B', 'C'])

A    3.0
B    3.0
C    3.0
dtype: float64

In [10]:
# Define a series
s = pd.Series([98,73,65],index=['Andrea', 'Beth', 'Carolina'])

# Divide each element in series by 10
print(s /10, '\n')

# Take the exponential of each element in series
print(np.exp(s), '\n')

# Original series is unchanged
print(s)

Andrea      9.8
Beth        7.3
Carolina    6.5
dtype: float64

Andrea      3.637971e+42
Beth        5.052394e+31
Carolina    1.694889e+28
dtype: float64

Andrea      98
Beth        73
Carolina    65
dtype: int64

In [11]:
s > 70

Andrea       True
Beth         True
Carolina    False
dtype: bool

In [12]:
# Series with NAs in it
s = pd.Series([1, 2, np.nan, 4, np.nan])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [13]:
# Check if series has NAs
s.hasnans

True

In [14]:
s.isna()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [18]:
# Check in:
# The integer number -999 is often used to represent missing values. 
# Create a pandas.Series named s with four integer values, two of which are -999. 
# The index of this series should be the letters A through D.

In [20]:
s = pd.Series([-999,73, -999, 65],index=['A', 'B', 'C', 'D'])
s

A   -999
B     73
C   -999
D     65
dtype: int64

In [ ]:
# Check in:
# In the pandas.Series documentation, look for the method mask(). 
# Use this method to update the series s so that the -999 values are 
# replaced by NA values. 
# HINT: check the first example in the method’s documentation.

In [25]:
s_masked = s.mask(s == -999) # mask() assigns NaN to -999
s_masked

A     NaN
B    73.0
C     NaN
D    65.0
dtype: float64

In [27]:
# Initialize dictionary with columns' data 
d = {'col_name_1' : pd.Series(np.arange(3)), # assigns variables to values 0-2
     'col_name_2' : pd.Series([3.1, 3.2, 3.3]), # sets variables as defined
     }

# Create data frame
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [28]:
# Change index
df.index = ['a','b','c']
df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

In [29]:
# Check in: We can access the data frame’s column names via the columns attribute. 
# Update the column names to C1 and C2 by updating this attribute.

In [30]:
df.columns = ['C1', 'C2']
df

   C1   C2
a   0  3.1
b   1  3.2
c   2  3.3